
import { GadgetRepository } from '../domain/interfaces/gadgetRepository'
import { CreateGadgetDto } from '../presentation/dto/createGadgetDto'
import { Gadget } from '../domain/entities/gadget'

export class GadgetsService {
    constructor(private gadgetRepository: GadgetRepository) {}

    async getAllGadgets() {
        return await this.gadgetRepository.findAll()
    }

    async createGadget(dto: CreateGadgetDto): Promise<Gadget> {
        const gadget: Gadget = {
            id: '', // This will be generated by the database
            name: dto.name,
            brand: dto.brand,
            releaseDate: dto.releaseDate,
        }
        return await this.gadgetRepository.create(gadget)
    }
}